# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.7
    commands:
      - echo Using Environment Variables
      - echo "--------------------------------------"
      - echo envName=${envName}
      - echo vpcCidr=${vpcCidr}
      - echo targetAssumeRoleArn=${targetAssumeRoleArn}
      - echo healthLakeEndpoint=${healthLakeEndpoint}
      - echo cdkAction=${cdkAction}
      - echo "--------------------------------------"
      - echo
      - echo Installing CDK and required dependencies
      - chmod +x codebuild/aws_assume_role.sh
      - chmod +x codebuild/create_import_acm_cert.sh
  pre_build:
    commands:
      - echo Validating and Assuming targetAssumeRoleArn=${targetAssumeRoleArn}
      - . ./codebuild/aws_assume_role.sh ${targetAssumeRoleArn}
      - aws sts get-caller-identity
      - . ./codebuild/create_import_acm_cert.sh
      - export fhirConvSelfSignedCertArn=${SELF_SIGNED_CERT_ACM_ARN}
      - echo
      - echo Installing source NPM dependencies...
      - npm install -g aws-cdk
      - npm install -g typescript
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - cdk bootstrap
      - CDK_BOOTSTRAP_BUCKET=$(aws s3 ls |grep cdktoolkit|head -1| awk '{print $NF}')
      - cdk synth
      - cd sam
      - sam build
      - cd ..
  post_build:
    commands:
      - echo Deploying / Updating CDK stacks
      - cdk ${cdkAction} --all --require-approval never --force
      - echo Deploying SFTP custom auth stack with an existing SAM template
      - echo Reusing CDK bootstrap bucket for sam temporary artifacts
      - cd sam
      - sam ${cdkAction} --no-confirm-changeset --s3-bucket ${CDK_BOOTSTRAP_BUCKET} --s3-prefix sam-sftp

